# site information
site_name: SharpShooters
site_url: https://guanqing-github.github.io/SharpShooters/
#site_description: Website for project: SharpShooters

# navigation
-nv:
  -Rotating Elves: index.md
  -Hand Exoskeleton: index.md
  
# theme
theme:
  name: material
  logo: Logo.png
  font:
   text: Playfair Display

# copyright
copyright: SharpShooters

