# site information
site_name: ROTATING ELVES
site_url: https://guanqing-github.github.io/Rotating-Elves/
#site_description: Website for project: Rotating Elves

# navigation
#-nv:
 # -Project Materials: test.md
# theme
theme:
  name: material
  logo: Logo.png
  font:
   text: Playfair Display

copyright: SharpShooters
link: mailto:<867151430@qq.com>
