# site information
site_name: SharpShooters
site_url: https://guanqing-github.github.io/SharpShooters/
site_description: Website recording projects by SharpShooters

# navigation
nav:
  -Rotating Elves: Rotating_Elves.md
  -Hand Exoskeleton: Hand_Exoskeleton.md
  -Automated Assembly Line: Automated_Line.md
  -Automatic Catapule: Automatic_Catapult.md
  
# theme
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  #logo: logo.png
  font:
   text: Playfair Display

# Copyright
copyright: Copyright &copy; SharpShooters

