# site information
site_name: SharpShooters
site_url: https://guanqing-github.github.io/SharpShooters/
#site_description: Website for projects by SharpShooters

# navigation
-nv:
  -Rotating Elves: Rotating Elves.md
  -Hand Exoskeleton: Hand Exoskeleton.md
  
# theme
theme:
  name: material
  #logo: logo.png
  font:
   text: Playfair Display

# copyright
copyright: SharpShooters

